### ISSUE TITLE
Please I have a problem 

### ISSUE THREAD

**Issue by IslamMachido** [gennariarmando/menu-map#1]
I have a problem when I click build an error message appears :

The E0135 class "CMenuManager" does not have a "m_nCurrentMenuScreen" member.

I hope you find the solution

**Comment by gennariarmando** [comment]
You need plugin-sdk in order to build this project.

**Comment by Alec-de-Boer** [comment]
This has nothing to do with not having plugin-sdk. Having it installed and configured correctly still doesn't make it work...
